[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.149.1"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "max-age=3600"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
